version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:8080"
    volumes:
      - type: bind
        source: ./backend
        target: /go/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    build: ./mysql
    platform: linux/x86_64
    hostname: ${DB_HOST}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_USER}",
          "-p${DB_PASS}",
        ]
      timeout: 10s
      interval: 10s
      retries: 3
      start_period: 30s

volumes:
  db_data:
